version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: track-finance-api
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=trackfinan
    #command: node --inspect=0.0.0.0:9229 -r ts-node/register -r tsconfig-paths/register src/main.ts #rodar com o debugger
    command: sh -c "npm run migrate && npm run start:dev"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - trackfinannet

  postgres:
    image: postgres:17
    volumes:  
      - track_finan_postgres:/var/lib/postgresql/data
    container_name: track_finan_postgres
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "trackfinan"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d trackfinan"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - trackfinannet

  # loki:
  #   image: grafana/loki:2.7.5
  #   ports:
  #     - "3100:3100"
  #   command: 
  #     - config.file=/etc/loki/local-config.yaml
  #     - print-config-stderr=true
  #   volumes:
  #     - ./loki-config.yaml:/etc/loki/loki-config.yaml
  #   networks:
  #     - trackfinannet

  # promtail:
  #   image: grafana/promtail:2.7.5
  #   volumes:
  #     - ./promtail/config/config.yaml:/etc/promtail/config.yaml
  #     - '/var/logs:/logs/syslogs'
  #     - ./logs:/logs 
  #     - './promtail/position:/position'
  #   ports: 
  #     - 9080:9080
  #   depends_on:
  #     - loki
  #     - app
  #   networks:
  #     - trackfinannet

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - loki
  #   networks:
  #     - trackfinannet
  
networks:
  trackfinannet:
    driver: bridge

volumes:
  track_finan_postgres:
