version: '3.8'
services:
  app:
    image: venilson/track-finance-api:latest
    container_name: track-finance-api
    env_file:
      - .env.prod
    command: node dist/main.js
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - trackfinannet
    restart: always

  postgres:
    image: postgres:16
    container_name: track_finan_postgres
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - track_finan_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trackfinannet
    restart: always

networks:
  trackfinannet:
    driver: bridge

volumes:
  track_finan_postgres:
    driver: local
